# Generated by Django 2.2.1 on 2019-06-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190602_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
